spring:
  application:
    name: zuul

server:
 port: 9002

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:9000/eureka/
zuul:
  routes:
   api:
    path: /API/**
    serviceId: ribbon

ribbon:
  ConnectionTimeout: 500
  ReadTimeout: 2000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

