server:
  port: 9004

spring:
  application:
    name: ribbon


eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:9000/eureka/


#zuul:
#  routes:
#   api:
#    path: /API/**
#    serviceId: service1
#
#ribbon:
#  ConnectionTimeout: 500
#  ReadTimeout: 2000
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 6000
